<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You are receiving this email because you (or someone pretending to be you) asked to send a new password to your account on web site.
If you did not ask to send the password, you should not pay attention to this letter, and if such mail continue to arrive, contact our administration.' => '',
    'After successful activation you can log in using the following password: ' => 'После успешной активации вы можете войти на сайт с таким паролем: ',
    'Before using the new password you have to activate it. Follow the link below: ' => 'Перед использованием нового пароля вы должны активировать его. Посетите следующую ссылку: ',
    'Hello, ' => 'Здраствуйте, ',
    'New password activation' => 'Активация нового пароля',
    'Oops, can\'t deliver letter to such email address.' => 'Упс, не возможно отправить письмо на такой email адрес.',
    'Order confirmation' => 'Подтверждение заказа',
    'Password: ' => 'Пароль: ',
    'Thanks, site administration.' => 'Спасибо, администрация сайта.',
];
